"""add email templates

Revision ID: 3ce26afb2548
Revises: b8670d1f6bf8
Create Date: 2025-11-19 00:57:19.895151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce26afb2548'
down_revision = 'b8670d1f6bf8'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_subject', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('invite_body', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reminder_subject', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reminder_body', sa.Text(), nullable=True))

    # seed existing row with defaults
    settings = sa.table(
        'system_settings',
        sa.column('id', sa.Integer),
        sa.column('invite_subject', sa.String),
        sa.column('invite_body', sa.Text),
        sa.column('reminder_subject', sa.String),
        sa.column('reminder_body', sa.Text),
    )
    bind = op.get_bind()
    bind.execute(
        settings.update().values(
            invite_subject="Your Votilio key for {{ election_name }}",
            invite_body="You are invited to vote in '{{ election_name }}'.\n\nKey: {{ voting_key }}\nVote link: {{ vote_url }}\n",
            reminder_subject="Reminder: vote in {{ election_name }}",
            reminder_body="Friendly reminder to vote in '{{ election_name }}'. Use key {{ voting_key }} at {{ vote_url }}.",
        )
    )

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.alter_column('invite_subject', existing_type=sa.String(length=255), nullable=False)
        batch_op.alter_column('invite_body', existing_type=sa.Text(), nullable=False)
        batch_op.alter_column('reminder_subject', existing_type=sa.String(length=255), nullable=False)
        batch_op.alter_column('reminder_body', existing_type=sa.Text(), nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_column('reminder_body')
        batch_op.drop_column('reminder_subject')
        batch_op.drop_column('invite_body')
        batch_op.drop_column('invite_subject')

    # ### end Alembic commands ###
