"""add timezone to settings

Revision ID: 9db801b5bcaf
Revises: 6b7ddfa24b2c
Create Date: 2025-11-21 04:42:51.515218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db801b5bcaf'
down_revision = '6b7ddfa24b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone_name', sa.String(length=128), nullable=False, server_default='UTC'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_column('timezone_name')

    # ### end Alembic commands ###
