"""add position ordering

Revision ID: b8670d1f6bf8
Revises: 36adfbef825b
Create Date: 2025-11-18 20:59:06.050235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8670d1f6bf8'
down_revision = '36adfbef825b'
branch_labels = None
depends_on = None


def upgrade():
    position_table = sa.table(
        'position',
        sa.column('id', sa.Integer),
        sa.column('election_id', sa.Integer),
        sa.column('order_index', sa.Integer),
    )

    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=True, server_default=sa.text('0')))

    bind = op.get_bind()
    rows = bind.execute(sa.select(position_table.c.id, position_table.c.election_id).order_by(position_table.c.election_id, position_table.c.id)).fetchall()
    current = {}
    for row in rows:
        idx = current.get(row.election_id, 0)
        bind.execute(
            position_table.update()
            .where(position_table.c.id == row.id)
            .values(order_index=idx)
        )
        current[row.election_id] = idx + 1

    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.alter_column('order_index', existing_type=sa.Integer(), nullable=False, server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.drop_column('order_index')

    # ### end Alembic commands ###
