"""add roles and election codes

Revision ID: d50dfec712f8
Revises: 2ad5724f7da1
Create Date: 2025-11-18 05:28:20.356309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50dfec712f8'
down_revision = '2ad5724f7da1'
branch_labels = None
depends_on = None


def upgrade():
    admin_table = sa.table(
        'admin_user',
        sa.column('id', sa.Integer),
        sa.column('is_super_admin', sa.Boolean),
    )
    election_table = sa.table(
        'election',
        sa.column('id', sa.Integer),
        sa.column('access_code', sa.String),
    )

    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_super_admin', sa.Boolean(), nullable=True, server_default=sa.text('false')))

    bind = op.get_bind()
    rows = bind.execute(sa.select(admin_table.c.id)).fetchall()
    if rows:
        # Promote the earliest admin to super admin by default.
        first_admin_id = min(row.id for row in rows)
        bind.execute(
            admin_table.update()
            .values(is_super_admin=False)
        )
        bind.execute(
            admin_table.update()
            .where(admin_table.c.id == first_admin_id)
            .values(is_super_admin=True)
        )

    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.alter_column('is_super_admin', nullable=False, server_default=None)

    with op.batch_alter_table('election', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_code', sa.String(length=32), nullable=True))

    rows = bind.execute(sa.select(election_table.c.id)).fetchall()
    for row in rows:
        generated_code = f'ELECTION{row.id}'
        bind.execute(
            election_table.update()
            .where(election_table.c.id == row.id)
            .values(access_code=generated_code)
        )

    with op.batch_alter_table('election', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_election_access_code', ['access_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('election', schema=None) as batch_op:
        batch_op.drop_constraint('uq_election_access_code', type_='unique')
        batch_op.drop_column('access_code')

    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.drop_column('is_super_admin')

    # ### end Alembic commands ###
